/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransactionsRouteImport } from './routes/_app.transactions'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLoansRouteImport } from './routes/_app.loans'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCardsRouteImport } from './routes/_app.cards'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app.transactions.index'
import { Route as AppTransactionsSendRouteImport } from './routes/_app.transactions.send'
import { Route as AppTransactionsReceiveRouteImport } from './routes/_app.transactions.receive'
import { Route as AppTransactionsIdRouteImport } from './routes/_app.transactions.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTransactionsRoute,
} as any)
const AppTransactionsSendRoute = AppTransactionsSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppTransactionsRoute,
} as any)
const AppTransactionsReceiveRoute = AppTransactionsReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AppTransactionsRoute,
} as any)
const AppTransactionsIdRoute = AppTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTransactionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof AppAccountsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/cards': typeof AppCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/loans': typeof AppLoansRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRouteWithChildren
  '/transactions/$id': typeof AppTransactionsIdRoute
  '/transactions/receive': typeof AppTransactionsReceiveRoute
  '/transactions/send': typeof AppTransactionsSendRoute
  '/transactions/': typeof AppTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof AppAccountsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/cards': typeof AppCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/loans': typeof AppLoansRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/transactions/$id': typeof AppTransactionsIdRoute
  '/transactions/receive': typeof AppTransactionsReceiveRoute
  '/transactions/send': typeof AppTransactionsSendRoute
  '/transactions': typeof AppTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/cards': typeof AppCardsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/loans': typeof AppLoansRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRouteWithChildren
  '/_app/transactions/$id': typeof AppTransactionsIdRoute
  '/_app/transactions/receive': typeof AppTransactionsReceiveRoute
  '/_app/transactions/send': typeof AppTransactionsSendRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/signup'
    | '/accounts'
    | '/analytics'
    | '/cards'
    | '/dashboard'
    | '/loans'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/transactions'
    | '/transactions/$id'
    | '/transactions/receive'
    | '/transactions/send'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/signup'
    | '/accounts'
    | '/analytics'
    | '/cards'
    | '/dashboard'
    | '/loans'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/transactions/$id'
    | '/transactions/receive'
    | '/transactions/send'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/signup'
    | '/_app/accounts'
    | '/_app/analytics'
    | '/_app/cards'
    | '/_app/dashboard'
    | '/_app/loans'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/transactions'
    | '/_app/transactions/$id'
    | '/_app/transactions/receive'
    | '/_app/transactions/send'
    | '/_app/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans': {
      id: '/_app/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards': {
      id: '/_app/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/_app/transactions/send': {
      id: '/_app/transactions/send'
      path: '/send'
      fullPath: '/transactions/send'
      preLoaderRoute: typeof AppTransactionsSendRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/_app/transactions/receive': {
      id: '/_app/transactions/receive'
      path: '/receive'
      fullPath: '/transactions/receive'
      preLoaderRoute: typeof AppTransactionsReceiveRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/_app/transactions/$id': {
      id: '/_app/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AppTransactionsIdRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
  }
}

interface AppTransactionsRouteChildren {
  AppTransactionsIdRoute: typeof AppTransactionsIdRoute
  AppTransactionsReceiveRoute: typeof AppTransactionsReceiveRoute
  AppTransactionsSendRoute: typeof AppTransactionsSendRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
}

const AppTransactionsRouteChildren: AppTransactionsRouteChildren = {
  AppTransactionsIdRoute: AppTransactionsIdRoute,
  AppTransactionsReceiveRoute: AppTransactionsReceiveRoute,
  AppTransactionsSendRoute: AppTransactionsSendRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
}

const AppTransactionsRouteWithChildren = AppTransactionsRoute._addFileChildren(
  AppTransactionsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCardsRoute: typeof AppCardsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLoansRoute: typeof AppLoansRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCardsRoute: AppCardsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLoansRoute: AppLoansRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
